security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:        plaintext
        App\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:           [ ROLE_USER ]
        ROLE_GODLIKE_ADMIN:   [ ROLE_ADMIN ]

    providers:
        bo_provider:
            chain :
                providers: [bo_memory_provider, bo_umbrella_provider]
        bo_memory_provider:
            memory:
                users:
                    umbrella:  { password: umbrella, roles: [ 'ROLE_GODLIKE_ADMIN']}
        bo_umbrella_provider:
            id: Umbrella\UserBundle\Security\UserProvider

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/password_request, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/password_reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false

        bo_firewall:
            pattern: ^/admin
            user_checker: Umbrella\UserBundle\Security\UserChecker
            anonymous: ~
            entry_point: Umbrella\UserBundle\Security\AuthenticationEntryPoint
            form_login:
                provider: bo_provider
                login_path: umbrella_user_login
                check_path: umbrella_user_login
                default_target_path: app_admin_default_index
            logout:
                path: umbrella_user_logout
                target: umbrella_user_login
