umbrella_core:
  webpack:
    dev_server_enable: "%env(bool:WEBPACK_SERVE)%"
  ckeditor:
    configs:
      custom:
        toolbar:
          - { name: links, items: [ 'Link', 'Unlink' ] }
        uiColor: '#FEFEFE'

umbrella_admin:
  menu:
    file: "../config/menu/admin_sidebar.yml"
  theme:
    name: "Umbrella"
  assets:
    script_entry: /build/admin.js
    stylesheet_entry: /build/admin.css
  filewriter:
    notification_enable: true