umbrella_core:
  ckeditor:
    configs:
      custom:
        toolbar:
          - { name: links, items: [ 'Link', 'Unlink' ] }
        uiColor: '#FEFEFE'

umbrella_admin:
  menu:
    file: "../config/menu/admin_sidebar.yml"
  theme:
    name: "Umbrella"
  assets:
    script_entry: admin
    stylesheet_entry: admin
  filewriter:
    notification_enable: true