umbrella_admin:
  resource: "@UmbrellaAdminBundle/Resources/config/routing.yml"
  prefix: /admin

umbrella_user:
  resource: "@UmbrellaUserBundle/Resources/config/routing.yml"
  prefix: /admin

app_:
  resource: "../../src/Controller/"
  type: annotation
  prefix: /

admin_:
  resource: "../../src/Controller/Admin/"
  type: annotation
  prefix: /admin