umbrella_user:
  resource: "@UmbrellaAdminBundle/Resources/config/user_routing.yml"
  prefix: /admin

umbrella_task:
  resource: "@UmbrellaAdminBundle/Resources/config/task_routing.yml"
  prefix: /admin

admin_:
  resource: "../../src/Controller/Admin/"
  type: annotation
  prefix: /admin