umbrella_user:
  resource: "@UmbrellaAdminBundle/Resources/config/user_routing.yml"
  prefix: /admin

app_:
  resource: "../../src/Controller/"
  type: annotation
  prefix: /

admin_:
  resource: "../../src/Controller/Admin/"
  type: annotation
  prefix: /admin