widget:
    type: title

datatables:
    icon: uil-table
    children:
        simple_datatable:
            route: app_admin_datatable_simple
        multiple_datatable:
            route: app_admin_datatable_multiple
        api_datatable:
            route: app_admin_datatable_api

ajax_handler_ctrl:
    icon: uil-exchange
    route: app_admin_ajaxhandler_index

forms:
    icon: uil-document-layout-center
    route: app_admin_form_index

base_ui:
    icon: uil-box
    children:
        icon_md:
            route: app_admin_icon_md
        toast:
            route: app_admin_toast_index

multi_level:
    icon: uil-folder-plus
    children:
        second_level:
            children:
                item1: {}
                item2: {}
        third_level:
            children:
                item1: {}
                item2:
                    children:
                        item11: {}
                        item12: {}

configuration:
    type: title

tasks:
    icon: uil-process
    route: umbrella_admin_task_index

users:
    icon: uil-user
    route: umbrella_admin_user_index

groups:
    icon: uil-users-alt
    route: umbrella_admin_usergroup_index
