umbrella_components:
    type: title

datatables:
    icon: uil-table
    children:
        simple_datatable:
            route: app_admin_datatable_simple
        multiple_datatable:
            route: app_admin_datatable_multiple
        api_datatable:
            route: app_admin_datatable_api
        tree_datatable:
            route: app_admin_datatable_tree
tasks:
    icon: uil-process
    route: app_admin_task_index

filewriter:
    icon: uil-file-plus-alt
    children:
        filewriter_simple:
            route: app_admin_filewriter_simple
        filewriter_datatable:
            route: app_admin_filewriter_datatable

js_response:
    icon: uil-exchange
    children:
        js_response_handler:
            route: app_admin_ajaxhandler_index

forms:
    icon: uil-document-layout-center
    route: app_admin_form_index

toast:
    icon: uil-chat
    route: app_admin_toast_index

ui:
    type: title

icon:
    icon: uil-streering
    children:
        icon_md:
            route: app_admin_icon_md
        icon_unicon:
            route: app_admin_icon_unicon

admin:
    type: title

admin_tasks:
    icon: uil-process
    route: umbrella_admin_task_index

users:
    icon: uil-user
    route: umbrella_admin_user_index

groups:
    icon: uil-users-alt
    route: umbrella_admin_usergroup_index
