monolog:
    handlers:
        app:
            level:  info
        main:
            type: fingers_crossed
            action_level: error
            handler: error
            excluded_http_codes: [404, 405]
        error:
            type: stream
            path: "%kernel.logs_dir%/error.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!php"]
