parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    #Menu
    App\Menu\CustomMenu:
        tags:
            - {name: umbrella.menu.factory, method: createMenu, alias: custom_menu}
            - {name: umbrella.menu.renderer, method: renderMenu, alias: custom_menu}
